// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_qmcDXZ19f_n0i9tnfXWWJDnpVJf8Jf0',
    appId: '1:665425256599:web:4bae8b9514fb2fe86fc9d2',
    messagingSenderId: '665425256599',
    projectId: 'fruits-hup-app',
    authDomain: 'fruits-hup-app.firebaseapp.com',
    storageBucket: 'fruits-hup-app.appspot.com',
    measurementId: 'G-Z5QP2PR0NC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0743cdAG8ACYKXaDdaLc08T1mOwHKit4',
    appId: '1:665425256599:android:579bfa1b6daddde56fc9d2',
    messagingSenderId: '665425256599',
    projectId: 'fruits-hup-app',
    storageBucket: 'fruits-hup-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl7HyXkJG-aqLJoRvYVxYISDg_k-DFUxQ',
    appId: '1:665425256599:ios:fc37c14d9efa9fb06fc9d2',
    messagingSenderId: '665425256599',
    projectId: 'fruits-hup-app',
    storageBucket: 'fruits-hup-app.appspot.com',
    iosBundleId: 'com.example.fruitsEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl7HyXkJG-aqLJoRvYVxYISDg_k-DFUxQ',
    appId: '1:665425256599:ios:fc37c14d9efa9fb06fc9d2',
    messagingSenderId: '665425256599',
    projectId: 'fruits-hup-app',
    storageBucket: 'fruits-hup-app.appspot.com',
    iosBundleId: 'com.example.fruitsEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_qmcDXZ19f_n0i9tnfXWWJDnpVJf8Jf0',
    appId: '1:665425256599:web:28fa2bf3ba0725a86fc9d2',
    messagingSenderId: '665425256599',
    projectId: 'fruits-hup-app',
    authDomain: 'fruits-hup-app.firebaseapp.com',
    storageBucket: 'fruits-hup-app.appspot.com',
    measurementId: 'G-Y93GQEWH1R',
  );
}
